/* ============================================================
   Arc90 — data layer
   100 habits · 10 categories · goal→habit suggestions
   Coach tips & Q&A (rule-based) · Protocol Tracker data
   ============================================================ */

const CATEGORIES = [
  { id: 'learn',   emoji: '📚', name: 'Learn & Grow' },
  { id: 'move',    emoji: '💪', name: 'Move & Train' },
  { id: 'eat',     emoji: '🥗', name: 'Eat Clean' },
  { id: 'money',   emoji: '💰', name: 'Money Smart' },
  { id: 'mind',    emoji: '🧘', name: 'Mind & Calm' },
  { id: 'work',    emoji: '💼', name: 'Career & Deep Work' },
  { id: 'sleep',   emoji: '😴', name: 'Sleep & Recover' },
  { id: 'create',  emoji: '🎨', name: 'Create & Express' },
  { id: 'connect', emoji: '❤️', name: 'Connect' },
  { id: 'home',    emoji: '🏡', name: 'Life Admin' },
  { id: 'custom',  emoji: '✨', name: 'Custom' },
];

const HABIT_LIBRARY = [
  // 📚 Learn & Grow
  { id: 1,  cat: 'learn',  emoji: '📖', name: 'Read 10 pages',                      min: 'Read 1 page' },
  { id: 2,  cat: 'learn',  emoji: '🎯', name: 'Study 1 focused hour',               min: 'Study 10 minutes' },
  { id: 3,  cat: 'learn',  emoji: '🗣️', name: 'Practice a language 15 min',         min: 'Practice 3 minutes' },
  { id: 4,  cat: 'learn',  emoji: '📝', name: 'Watch one tutorial & take notes',    min: 'Watch 5 minutes' },
  { id: 5,  cat: 'learn',  emoji: '🃏', name: 'Review flashcards',                  min: 'Review 5 cards' },
  { id: 6,  cat: 'learn',  emoji: '✍️', name: 'Summarize what you learned today',   min: 'Write one sentence' },
  { id: 7,  cat: 'learn',  emoji: '🎧', name: 'Listen to an educational podcast',   min: 'Listen 5 minutes' },
  { id: 8,  cat: 'learn',  emoji: '🎓', name: 'Complete one course module',         min: 'Open the course' },
  { id: 9,  cat: 'learn',  emoji: '💻', name: 'Practice coding 30 min',             min: 'Code 5 minutes' },
  { id: 10, cat: 'learn',  emoji: '🧑‍🏫', name: 'Teach someone one thing you learned', min: 'Share one fact' },
  // 💪 Move & Train
  { id: 11, cat: 'move',   emoji: '🏋️', name: 'Work out 30 min',                    min: '5-minute session' },
  { id: 12, cat: 'move',   emoji: '🚶', name: 'Hit 8,000 steps',                    min: '10-minute walk' },
  { id: 13, cat: 'move',   emoji: '🤸', name: 'Morning stretch 10 min',             min: 'Stretch 2 minutes' },
  { id: 14, cat: 'move',   emoji: '💥', name: 'Do 20 push-ups',                     min: '5 push-ups' },
  { id: 15, cat: 'move',   emoji: '🏃', name: 'Run 2 km',                           min: 'Run 5 minutes' },
  { id: 16, cat: 'move',   emoji: '🧘‍♀️', name: 'Yoga or pilates session',            min: '3 poses' },
  { id: 17, cat: 'move',   emoji: '🪜', name: 'Take the stairs every time',         min: 'One flight today' },
  { id: 18, cat: 'move',   emoji: '🌙', name: 'Walk after dinner',                  min: 'Walk to the corner' },
  { id: 19, cat: 'move',   emoji: '🦵', name: 'Mobility / foam roll 10 min',        min: 'Roll 2 minutes' },
  { id: 20, cat: 'move',   emoji: '🥇', name: 'Follow your training plan',          min: 'Do the warm-up' },
  // 🥗 Eat Clean
  { id: 21, cat: 'eat',    emoji: '🍳', name: 'Cook at home — no takeout',          min: 'Cook one meal' },
  { id: 22, cat: 'eat',    emoji: '🥦', name: 'Eat 2 servings of vegetables',       min: 'One serving' },
  { id: 23, cat: 'eat',    emoji: '💧', name: 'Drink 2L of water',                  min: 'One full glass now' },
  { id: 24, cat: 'eat',    emoji: '🥤', name: 'Zero sugary drinks',                 min: 'Swap one for water' },
  { id: 25, cat: 'eat',    emoji: '🍗', name: 'Protein with every meal',            min: 'Protein at one meal' },
  { id: 26, cat: 'eat',    emoji: '⏰', name: 'No snacking after 9pm',              min: 'Kitchen closed at 10' },
  { id: 27, cat: 'eat',    emoji: '💊', name: 'Take your vitamins',                 min: 'Take them' },
  { id: 28, cat: 'eat',    emoji: '🍎', name: 'Fruit instead of dessert',           min: 'Once today' },
  { id: 29, cat: 'eat',    emoji: '🥪', name: "Pack tomorrow's lunch",              min: 'Pack one item' },
  { id: 30, cat: 'eat',    emoji: '🍽️', name: 'Eat one meal without screens',       min: 'First 5 minutes' },
  // 💰 Money Smart
  { id: 31, cat: 'money',  emoji: '🔒', name: 'No-spend day',                       min: 'No impulse buys' },
  { id: 32, cat: 'money',  emoji: '🧾', name: 'Log every expense',                  min: 'Log the biggest one' },
  { id: 33, cat: 'money',  emoji: '☕', name: 'Make coffee at home',                min: 'Skip one bought coffee' },
  { id: 34, cat: 'money',  emoji: '🏦', name: 'Move $5 to savings',                 min: 'Move $1' },
  { id: 35, cat: 'money',  emoji: '⏳', name: '24-hour rule on impulse buys',       min: 'Wait 1 hour' },
  { id: 36, cat: 'money',  emoji: '🔍', name: 'Audit one subscription',             min: 'Open the list' },
  { id: 37, cat: 'money',  emoji: '📋', name: 'Stick to your grocery list',         min: 'Write the list' },
  { id: 38, cat: 'money',  emoji: '📦', name: 'Sell or donate one item',            min: 'Pick the item' },
  { id: 39, cat: 'money',  emoji: '📈', name: 'Read 10 min about money',            min: 'Read one article intro' },
  { id: 40, cat: 'money',  emoji: '👀', name: 'Check your account balance',         min: 'Open the app' },
  // 🧘 Mind & Calm
  { id: 41, cat: 'mind',   emoji: '🧘', name: 'Meditate 10 min',                    min: '10 slow breaths' },
  { id: 42, cat: 'mind',   emoji: '📓', name: 'Journal 5 min',                      min: 'Write one line' },
  { id: 43, cat: 'mind',   emoji: '🙏', name: "Write 3 things you're grateful for", min: 'Write one' },
  { id: 44, cat: 'mind',   emoji: '🌬️', name: '5 deep breaths before screens',      min: 'One deep breath' },
  { id: 45, cat: 'mind',   emoji: '🌅', name: 'No phone for first 30 min of day',   min: 'First 5 minutes' },
  { id: 46, cat: 'mind',   emoji: '📵', name: 'Digital sunset 1h before bed',       min: '15 minutes before' },
  { id: 47, cat: 'mind',   emoji: '🍃', name: 'Take a mindful walk',                min: '5 minutes outside' },
  { id: 48, cat: 'mind',   emoji: '🧠', name: "Brain-dump tomorrow's worries",      min: 'Write the top one' },
  { id: 49, cat: 'mind',   emoji: '💬', name: 'Say your affirmation out loud',      min: 'Once' },
  { id: 50, cat: 'mind',   emoji: '🩺', name: 'Do a 1-min body-scan check-in',      min: '20 seconds' },
  // 💼 Career & Deep Work
  { id: 51, cat: 'work',   emoji: '⚡', name: 'One 90-min deep work block',         min: 'One 25-min block' },
  { id: 52, cat: 'work',   emoji: '🗒️', name: "Plan tomorrow's top 3 tasks",        min: 'Write task #1' },
  { id: 53, cat: 'work',   emoji: '📬', name: 'Inbox to zero',                      min: 'Clear 10 emails' },
  { id: 54, cat: 'work',   emoji: '🤝', name: 'Message one person in your network', min: 'Draft the message' },
  { id: 55, cat: 'work',   emoji: '💼', name: 'Polish portfolio / CV 15 min',       min: 'Fix one line' },
  { id: 56, cat: 'work',   emoji: '🛠️', name: 'Learn one work skill 20 min',        min: '5 minutes' },
  { id: 57, cat: 'work',   emoji: '🙅', name: 'No social media during work hours',  min: 'Phone in another room 1h' },
  { id: 58, cat: 'work',   emoji: '🍅', name: 'Four pomodoros before lunch',        min: 'One pomodoro' },
  { id: 59, cat: 'work',   emoji: '🔁', name: 'Ask for one piece of feedback',      min: 'Pick who to ask' },
  { id: 60, cat: 'work',   emoji: '🚀', name: 'Ship one small thing',               min: 'Ship one fix' },
  // 😴 Sleep & Recover
  { id: 61, cat: 'sleep',  emoji: '🛏️', name: 'In bed by 11pm',                     min: 'In bed by 11:30' },
  { id: 62, cat: 'sleep',  emoji: '🌄', name: 'Wake at the same time daily',        min: 'Within 30 minutes' },
  { id: 63, cat: 'sleep',  emoji: '🚫', name: 'No caffeine after 2pm',              min: 'None after 4pm' },
  { id: 64, cat: 'sleep',  emoji: '🌚', name: 'No screens in bed',                  min: 'Phone out of reach' },
  { id: 65, cat: 'sleep',  emoji: '😴', name: 'Sleep 7+ hours',                     min: 'Lights out 15 min earlier' },
  { id: 66, cat: 'sleep',  emoji: '🕯️', name: 'Evening wind-down ritual',           min: '5-minute version' },
  { id: 67, cat: 'sleep',  emoji: '☀️', name: 'Morning sunlight 10 min',            min: '2 minutes outside' },
  { id: 68, cat: 'sleep',  emoji: '⏱️', name: 'Nap 20 min max',                     min: 'Set the alarm' },
  { id: 69, cat: 'sleep',  emoji: '❄️', name: 'Prep bedroom: cool & dark',          min: 'Curtains + window' },
  { id: 70, cat: 'sleep',  emoji: '🍷', name: 'No alcohol on weeknights',           min: 'Not tonight' },
  // 🎨 Create & Express
  { id: 71, cat: 'create', emoji: '🖊️', name: 'Write 200 words',                    min: 'Write one paragraph' },
  { id: 72, cat: 'create', emoji: '✏️', name: 'Sketch or draw 15 min',              min: 'One small sketch' },
  { id: 73, cat: 'create', emoji: '🎸', name: 'Practice your instrument 20 min',    min: 'Play one song' },
  { id: 74, cat: 'create', emoji: '📷', name: 'Take one intentional photo',         min: 'One photo' },
  { id: 75, cat: 'create', emoji: '🧪', name: 'Side project 30 min',                min: 'Open it, 5 minutes' },
  { id: 76, cat: 'create', emoji: '💡', name: 'Brainstorm 10 ideas',                min: '3 ideas' },
  { id: 77, cat: 'create', emoji: '🔧', name: "Refine yesterday's work",            min: 'One small fix' },
  { id: 78, cat: 'create', emoji: '🌍', name: 'Share one creation publicly',        min: 'Share with one person' },
  { id: 79, cat: 'create', emoji: '🧩', name: 'Learn one new technique',            min: 'Watch one example' },
  { id: 80, cat: 'create', emoji: '🖼️', name: 'Consume art for inspiration 15 min', min: '5 minutes' },
  // ❤️ Connect
  { id: 81, cat: 'connect', emoji: '📞', name: 'Call or text someone you love',     min: 'One text' },
  { id: 82, cat: 'connect', emoji: '🌟', name: 'Give one genuine compliment',       min: 'One compliment' },
  { id: 83, cat: 'connect', emoji: '🙌', name: 'Phones away at the table',          min: 'First 10 minutes' },
  { id: 84, cat: 'connect', emoji: '🫶', name: 'Do one small act of kindness',      min: 'Hold the door' },
  { id: 85, cat: 'connect', emoji: '👋', name: 'Check in on a friend',              min: 'One message' },
  { id: 86, cat: 'connect', emoji: '💌', name: 'Write a thank-you message',         min: 'One sentence' },
  { id: 87, cat: 'connect', emoji: '🌐', name: 'Make one new connection',           min: 'Say hi to someone' },
  { id: 88, cat: 'connect', emoji: '👨‍👩‍👧', name: 'Eat dinner with family / friends', min: 'Sit together 10 min' },
  { id: 89, cat: 'connect', emoji: '🗓️', name: 'Plan quality time this week',       min: 'Propose a day' },
  { id: 90, cat: 'connect', emoji: '👂', name: 'Listen without interrupting',       min: 'One conversation' },
  // 🏡 Life Admin
  { id: 91, cat: 'home',   emoji: '🛌', name: 'Make your bed',                      min: 'Pull the cover up' },
  { id: 92, cat: 'home',   emoji: '⏲️', name: '10-minute tidy',                     min: '2-minute tidy' },
  { id: 93, cat: 'home',   emoji: '🧽', name: 'Dishes done before bed',             min: 'Just your plate' },
  { id: 94, cat: 'home',   emoji: '👕', name: "Lay out tomorrow's clothes",         min: 'Pick the shirt' },
  { id: 95, cat: 'home',   emoji: '🪴', name: 'Water the plants',                   min: 'The thirsty one' },
  { id: 96, cat: 'home',   emoji: '🧹', name: 'Clear one surface',                  min: 'One corner' },
  { id: 97, cat: 'home',   emoji: '🧺', name: 'Complete one laundry cycle',         min: 'Start the load' },
  { id: 98, cat: 'home',   emoji: '📅', name: '5-min calendar & budget review',     min: 'Glance at tomorrow' },
  { id: 99, cat: 'home',   emoji: '🔨', name: 'Fix or finish one small thing',      min: 'Pick the thing' },
  { id: 100, cat: 'home',  emoji: '🗑️', name: 'Take out trash & reset kitchen',     min: 'Trash only' },
  // — extended library —
  { id: 101, cat: 'learn',  emoji: '📑', name: 'Read one long-form article',         min: 'Read the intro' },
  { id: 102, cat: 'learn',  emoji: '🧩', name: 'Solve one practice problem',         min: 'Read the problem' },
  { id: 103, cat: 'learn',  emoji: '🎙️', name: 'Explain a concept out loud',         min: 'One sentence' },
  { id: 104, cat: 'move',   emoji: '🏊', name: 'Swim or cardio 20 min',              min: 'Move 5 minutes' },
  { id: 105, cat: 'move',   emoji: '🧗', name: 'Train grip / pull-ups',              min: 'One dead hang' },
  { id: 106, cat: 'move',   emoji: '🚲', name: 'Cycle 20 min',                       min: 'Ride 5 minutes' },
  { id: 107, cat: 'eat',    emoji: '🥚', name: 'High-protein breakfast',             min: 'One egg' },
  { id: 108, cat: 'eat',    emoji: '🧂', name: 'No ultra-processed food today',      min: 'One clean meal' },
  { id: 109, cat: 'eat',    emoji: '🍵', name: 'Swap a coffee for tea or water',     min: 'Once today' },
  { id: 110, cat: 'money',  emoji: '💳', name: 'Review yesterday’s spending',        min: 'Glance at it' },
  { id: 111, cat: 'money',  emoji: '🎯', name: 'Add to one financial goal',          min: 'Move $1' },
  { id: 112, cat: 'money',  emoji: '🛒', name: 'Unsubscribe from a shopping email',  min: 'Open the inbox' },
  { id: 113, cat: 'mind',   emoji: '🌅', name: 'Sunlight within 30 min of waking',   min: 'Step outside' },
  { id: 114, cat: 'mind',   emoji: '📵', name: 'One hour fully offline',             min: '10 minutes off' },
  { id: 115, cat: 'mind',   emoji: '💭', name: 'Write a worry down and park it',     min: 'Name it' },
  { id: 116, cat: 'sleep',  emoji: '🌑', name: 'In bed by your target time',         min: '15 min earlier' },
  { id: 117, cat: 'sleep',  emoji: '📴', name: 'Phone out of the bedroom',           min: 'Across the room' },
  { id: 118, cat: 'sleep', emoji: '🌬️', name: 'Do 4-7-8 breathing in bed', min: 'Do one 4-7-8 breath' },
  { id: 119, cat: 'work',   emoji: '🎯', name: 'Define your one priority',           min: 'Name it' },
  { id: 120, cat: 'work',   emoji: '🍅', name: 'Single-task for 25 minutes',         min: 'One Pomodoro' },
  { id: 121, cat: 'work',   emoji: '🌙', name: 'End-of-day shutdown ritual',         min: 'Close the tabs' },
  { id: 122, cat: 'connect', emoji: '✉️', name: 'Send an encouraging message',       min: 'One text' },
  { id: 123, cat: 'connect', emoji: '📞', name: 'Call someone you miss',             min: 'Two-minute call' },
  { id: 124, cat: 'connect', emoji: '🏡', name: 'Chat with a neighbor 5 minutes', min: 'Wave to one neighbor' },
  { id: 125, cat: 'create', emoji: '🎨', name: 'Make something for 20 min',          min: 'Create 5 minutes' },
  { id: 126, cat: 'create', emoji: '💡', name: 'Capture 3 new ideas',               min: 'One idea' },
  { id: 127, cat: 'create', emoji: '📷', name: 'Document your progress',             min: 'One photo' },
  { id: 128, cat: 'home',   emoji: '🧴', name: 'Declutter 5 items',                  min: 'One item' },
  { id: 129, cat: 'home',   emoji: '🛏️', name: 'Reset your space before bed',        min: 'Clear one surface' },
  { id: 130, cat: 'home',   emoji: '📥', name: 'Desk / inbox to zero',              min: 'File 3 things' },
  // Expanded library (v164): 40 habits per category, 400 in total.
  { id: 131, cat: 'learn', emoji: '🧭', name: 'Pick today\'s learning goal', min: 'Name one thing to learn' },
  { id: 132, cat: 'learn', emoji: '🔤', name: 'Learn 5 new vocabulary words', min: 'Learn 1 new word' },
  { id: 133, cat: 'learn', emoji: '🧠', name: 'Learn one mental model', min: 'Skim one mental model' },
  { id: 134, cat: 'learn', emoji: '♟️', name: 'Solve one chess puzzle', min: 'Study one chess position' },
  { id: 135, cat: 'learn', emoji: '🧮', name: 'Do mental math for 5 minutes', min: 'Solve one sum in your head' },
  { id: 136, cat: 'learn', emoji: '🎬', name: 'Watch a documentary 20 min', min: 'Watch a documentary 5 min' },
  { id: 137, cat: 'learn', emoji: '🔁', name: 'Review yesterday\'s notes 10 min', min: 'Reread one note' },
  { id: 138, cat: 'learn', emoji: '🗺️', name: 'Mind map one topic', min: 'Write one central idea' },
  { id: 139, cat: 'learn', emoji: '🔎', name: 'Research one question 15 min', min: 'Look up one question' },
  { id: 140, cat: 'learn', emoji: '🏛️', name: 'Learn one historical event', min: 'Read one history fact' },
  { id: 141, cat: 'learn', emoji: '🌍', name: 'Read about another culture 10 min', min: 'Read one fact about a culture' },
  { id: 142, cat: 'learn', emoji: '🔭', name: 'Learn one science concept', min: 'Read one science fact' },
  { id: 143, cat: 'learn', emoji: '🙋', name: 'Ask an expert one question', min: 'Draft one question to ask' },
  { id: 144, cat: 'learn', emoji: '💬', name: 'Discuss one idea with someone', min: 'Text one idea to a friend' },
  { id: 145, cat: 'learn', emoji: '⌨️', name: 'Practice typing 10 minutes', min: 'Type for 2 minutes' },
  { id: 146, cat: 'learn', emoji: '💻', name: 'Read someone else\'s code 15 min', min: 'Read 10 lines of code' },
  { id: 147, cat: 'learn', emoji: '📊', name: 'Learn one spreadsheet formula', min: 'Try one simple formula' },
  { id: 148, cat: 'learn', emoji: '🤟', name: 'Learn 3 sign language signs', min: 'Learn 1 sign' },
  { id: 149, cat: 'learn', emoji: '🌿', name: 'Identify one plant or bird', min: 'Notice one plant or bird' },
  { id: 150, cat: 'learn', emoji: '🧩', name: 'Do one crossword puzzle', min: 'Solve 3 crossword clues' },
  { id: 151, cat: 'learn', emoji: '⚖️', name: 'Argue the opposing view 5 min', min: 'Write one counterpoint' },
  { id: 152, cat: 'learn', emoji: '📜', name: 'Copy a great paragraph by hand', min: 'Copy one sentence by hand' },
  { id: 153, cat: 'learn', emoji: '🪶', name: 'Read one poem aloud', min: 'Read one stanza aloud' },
  { id: 154, cat: 'learn', emoji: '❓', name: 'Note one thing that confused you', min: 'Name one confusing point' },
  { id: 155, cat: 'learn', emoji: '🍳', name: 'Learn one cooking technique', min: 'Look up one technique' },
  { id: 156, cat: 'learn', emoji: '🧷', name: 'Memorize one quote or fact', min: 'Repeat one fact twice' },
  { id: 157, cat: 'learn', emoji: '🛠️', name: 'Learn the basics of one tool', min: 'Open one how-to page' },
  { id: 158, cat: 'move', emoji: '🌅', name: 'Morning walk 20 minutes', min: 'Walk 5 minutes after waking' },
  { id: 159, cat: 'move', emoji: '🏋️', name: 'Do 30 bodyweight squats', min: 'Do 5 squats' },
  { id: 160, cat: 'move', emoji: '🪵', name: 'Hold a plank for 1 minute', min: 'Plank for 10 seconds' },
  { id: 161, cat: 'move', emoji: '🦵', name: 'Do 3 sets of 10 lunges', min: 'Do 5 lunges per leg' },
  { id: 162, cat: 'move', emoji: '⏱️', name: 'Stand and move every hour', min: 'Stand up and stretch once' },
  { id: 163, cat: 'move', emoji: '💃', name: 'Dance for 10 minutes', min: 'Dance to one song' },
  { id: 164, cat: 'move', emoji: '🪢', name: 'Jump rope 5 minutes', min: 'Jump rope 30 seconds' },
  { id: 165, cat: 'move', emoji: '🤸', name: 'Do 100 jumping jacks', min: 'Do 10 jumping jacks' },
  { id: 166, cat: 'move', emoji: '🌉', name: 'Do 20 glute bridges', min: 'Do 5 glute bridges' },
  { id: 167, cat: 'move', emoji: '🧱', name: 'Wall sit for 1 minute', min: 'Wall sit for 15 seconds' },
  { id: 168, cat: 'move', emoji: '🏃', name: 'Run 6 one-minute intervals', min: 'Run 1 one-minute interval' },
  { id: 169, cat: 'move', emoji: '🚲', name: 'Bike or walk for one errand', min: 'Walk to one nearby place' },
  { id: 170, cat: 'move', emoji: '🦩', name: 'Balance on one leg 2 minutes', min: 'Balance 20 seconds per leg' },
  { id: 171, cat: 'move', emoji: '💪', name: 'Do 15 chair dips', min: 'Do 3 chair dips' },
  { id: 172, cat: 'move', emoji: '🔥', name: 'Do 10 burpees', min: 'Do 2 burpees' },
  { id: 173, cat: 'move', emoji: '📞', name: 'Walk during a phone call', min: 'Walk 5 min during a call' },
  { id: 174, cat: 'move', emoji: '⚡', name: 'Do a 10-minute core circuit', min: 'Do 1 core exercise' },
  { id: 175, cat: 'move', emoji: '⚽', name: 'Play an active game or sport', min: 'Play a sport for 5 minutes' },
  { id: 176, cat: 'move', emoji: '⛰️', name: 'Do 20 mountain climbers', min: 'Do 5 mountain climbers' },
  { id: 177, cat: 'move', emoji: '📺', name: 'Move during every TV break', min: 'Do 5 squats in one break' },
  { id: 178, cat: 'move', emoji: '🦶', name: 'Do 30 calf raises', min: 'Do 10 calf raises' },
  { id: 179, cat: 'move', emoji: '🤝', name: 'Exercise with a friend', min: 'Walk 5 minutes with someone' },
  { id: 180, cat: 'move', emoji: '🍃', name: 'Do 10 minutes of tai chi', min: 'Do 2 minutes of tai chi' },
  { id: 181, cat: 'move', emoji: '🧘', name: 'Hold a deep squat 2 minutes', min: 'Hold a deep squat 20 seconds' },
  { id: 182, cat: 'move', emoji: '📝', name: 'Log today\'s workout', min: 'Write down one exercise' },
  { id: 183, cat: 'move', emoji: '🥊', name: 'Shadowbox for 5 minutes', min: 'Shadowbox for 1 minute' },
  { id: 184, cat: 'move', emoji: '🪜', name: 'Do 20 step-ups', min: 'Do 5 step-ups' },
  { id: 185, cat: 'eat', emoji: '🌾', name: 'Eat a whole grain today', min: 'Swap in one whole grain' },
  { id: 186, cat: 'eat', emoji: '🫘', name: 'Eat beans or lentils today', min: 'Add a spoonful of beans' },
  { id: 187, cat: 'eat', emoji: '🎒', name: 'Pack a healthy snack', min: 'Put one snack in your bag' },
  { id: 188, cat: 'eat', emoji: '🐢', name: 'Take 20 minutes for one meal', min: 'Chew slowly for 3 bites' },
  { id: 189, cat: 'eat', emoji: '🍽️', name: 'Stop eating at comfortably full', min: 'Pause once to check fullness' },
  { id: 190, cat: 'eat', emoji: '📅', name: 'Plan tomorrow\'s meals', min: 'Write down one meal' },
  { id: 191, cat: 'eat', emoji: '🔪', name: 'Prep one ingredient ahead', min: 'Wash one piece of produce' },
  { id: 192, cat: 'eat', emoji: '🫙', name: 'Eat a fermented food', min: 'Have one fermented bite' },
  { id: 193, cat: 'eat', emoji: '🍎', name: 'Eat 2 pieces of fruit', min: 'Eat 1 piece of fruit' },
  { id: 194, cat: 'eat', emoji: '🌿', name: 'Season a meal with herbs', min: 'Add one herb or spice' },
  { id: 195, cat: 'eat', emoji: '📓', name: 'Log your meals today', min: 'Log one meal' },
  { id: 196, cat: 'eat', emoji: '🍲', name: 'Cook extra for leftovers', min: 'Save one portion for later' },
  { id: 197, cat: 'eat', emoji: '🍛', name: 'Build one balanced plate', min: 'Add one missing food group' },
  { id: 198, cat: 'eat', emoji: '🤔', name: 'Check hunger before snacking', min: 'Pause 1 minute before a snack' },
  { id: 199, cat: 'eat', emoji: '🌱', name: 'Eat 5 different plant foods', min: 'Add one extra plant food' },
  { id: 200, cat: 'eat', emoji: '🏷️', name: 'Read 3 nutrition labels', min: 'Read one nutrition label' },
  { id: 201, cat: 'eat', emoji: '🥦', name: 'Eat a plant-based meal', min: 'Make one dish meat-free' },
  { id: 202, cat: 'eat', emoji: '🥣', name: 'Portion snacks into a bowl', min: 'Pour one snack into a bowl' },
  { id: 203, cat: 'eat', emoji: '🫐', name: 'Make a homemade smoothie', min: 'Blend one fruit and veg' },
  { id: 204, cat: 'eat', emoji: '🫶', name: 'Share a meal with someone', min: 'Eat one snack with someone' },
  { id: 205, cat: 'eat', emoji: '🍬', name: 'Keep sweets out of sight', min: 'Move one treat out of view' },
  { id: 206, cat: 'eat', emoji: '⏰', name: 'Eat meals at regular times', min: 'Eat one meal on schedule' },
  { id: 207, cat: 'eat', emoji: '🧂', name: 'Taste before adding salt', min: 'Taste one dish before salting' },
  { id: 208, cat: 'eat', emoji: '🪑', name: 'Eat every meal sitting down', min: 'Sit down for one snack' },
  { id: 209, cat: 'eat', emoji: '🌰', name: 'Snack on nuts or seeds', min: 'Eat a few nuts or seeds' },
  { id: 210, cat: 'eat', emoji: '🥔', name: 'Choose baked over fried food', min: 'Swap one fried item' },
  { id: 211, cat: 'eat', emoji: '🐟', name: 'Eat an omega-3-rich food', min: 'Add a spoonful of ground flax' },
  { id: 212, cat: 'money', emoji: '🥫', name: 'Plan meals from your pantry', min: 'Check what\'s in the pantry' },
  { id: 213, cat: 'money', emoji: '🍲', name: 'Eat leftovers first', min: 'Eat one leftover portion' },
  { id: 214, cat: 'money', emoji: '🧠', name: 'Learn one money term', min: 'Read one definition' },
  { id: 215, cat: 'money', emoji: '🫙', name: 'Drop spare change in a jar', min: 'Add one coin to the jar' },
  { id: 216, cat: 'money', emoji: '⚖️', name: 'Compare prices before buying', min: 'Check one price' },
  { id: 217, cat: 'money', emoji: '📆', name: 'Check bills due this week', min: 'Look at one due date' },
  { id: 218, cat: 'money', emoji: '🏆', name: 'Write down 3 money wins', min: 'Name one money win' },
  { id: 219, cat: 'money', emoji: '💭', name: 'Journal one money feeling', min: 'Name one money feeling' },
  { id: 220, cat: 'money', emoji: '♻️', name: 'Use up something you own', min: 'Pick one item to use up' },
  { id: 221, cat: 'money', emoji: '🔌', name: 'Switch off devices not in use', min: 'Switch off one device' },
  { id: 222, cat: 'money', emoji: '🤔', name: 'Ask need or want before buying', min: 'Ask need or want once' },
  { id: 223, cat: 'money', emoji: '💵', name: 'Pay cash for daily spending', min: 'Pay cash once today' },
  { id: 224, cat: 'money', emoji: '🎉', name: 'Plan one free fun activity', min: 'List one free idea' },
  { id: 225, cat: 'money', emoji: '📞', name: 'Ask to lower one bill', min: 'Find one bill to lower' },
  { id: 226, cat: 'money', emoji: '🤝', name: 'Borrow instead of buying', min: 'Ask to borrow one thing' },
  { id: 227, cat: 'money', emoji: '🛒', name: 'Empty your online cart', min: 'Remove one cart item' },
  { id: 228, cat: 'money', emoji: '⏱️', name: 'Price purchases in work hours', min: 'Convert one price' },
  { id: 229, cat: 'money', emoji: '🏷️', name: 'Use one coupon or discount', min: 'Look for one discount' },
  { id: 230, cat: 'money', emoji: '🗣️', name: 'Talk money with someone', min: 'Share one money thought' },
  { id: 231, cat: 'money', emoji: '📉', name: 'Pay extra toward one debt', min: 'Add $1 to a debt payment' },
  { id: 232, cat: 'money', emoji: '📁', name: 'File one money document', min: 'File one paper' },
  { id: 233, cat: 'money', emoji: '🗺️', name: 'Batch errands into one trip', min: 'Group two errands' },
  { id: 234, cat: 'money', emoji: '🎚️', name: 'Set a daily spending cap', min: 'Pick a cap for today' },
  { id: 235, cat: 'money', emoji: '✂️', name: 'Spot one fee you can avoid', min: 'Check one statement line' },
  { id: 236, cat: 'money', emoji: '🧭', name: 'Revisit your savings why', min: 'Read your savings why' },
  { id: 237, cat: 'money', emoji: '💡', name: 'Brainstorm one income idea', min: 'Write one idea down' },
  { id: 238, cat: 'money', emoji: '🛒', name: 'Plan this week\'s purchases', min: 'List one planned purchase' },
  { id: 239, cat: 'mind', emoji: '🎯', name: 'Set a daily intention', min: 'Pick one word for today' },
  { id: 240, cat: 'mind', emoji: '🫁', name: 'Box breathe for 4 minutes', min: 'Box breathe for 1 round' },
  { id: 241, cat: 'mind', emoji: '🍵', name: 'Sip a warm drink mindfully', min: 'Take 3 mindful sips' },
  { id: 242, cat: 'mind', emoji: '🌳', name: 'Spend 20 minutes in nature', min: 'Step outside for 2 minutes' },
  { id: 243, cat: 'mind', emoji: '🧩', name: 'Do a crossword or sudoku', min: 'Solve 3 puzzle clues' },
  { id: 244, cat: 'mind', emoji: '🎵', name: 'Listen to calming music 10 min', min: 'Listen to one calm song' },
  { id: 245, cat: 'mind', emoji: '💗', name: 'Practice loving-kindness 5 min', min: 'Wish one person well' },
  { id: 246, cat: 'mind', emoji: '🏷️', name: 'Name your feelings 3 times', min: 'Name one feeling right now' },
  { id: 247, cat: 'mind', emoji: '👀', name: 'Take a screen break every hour', min: 'Take one 1-min screen break' },
  { id: 248, cat: 'mind', emoji: '☁️', name: 'Watch the sky for 5 minutes', min: 'Look at the sky for 1 minute' },
  { id: 249, cat: 'mind', emoji: '🔄', name: 'Reframe one negative thought', min: 'Spot one unhelpful thought' },
  { id: 250, cat: 'mind', emoji: '🎤', name: 'Sing a song you love', min: 'Hum for 30 seconds' },
  { id: 251, cat: 'mind', emoji: '⏸️', name: 'Pause 5 minutes at midday', min: 'Pause 1 minute at midday' },
  { id: 252, cat: 'mind', emoji: '💆', name: 'Relax jaw and shoulders 3 times', min: 'Drop your shoulders once' },
  { id: 253, cat: 'mind', emoji: '🧽', name: 'Do one chore mindfully', min: 'Wash one dish mindfully' },
  { id: 254, cat: 'mind', emoji: '📊', name: 'Rate your mood each evening', min: 'Rate your mood 1 to 5' },
  { id: 255, cat: 'mind', emoji: '📜', name: 'Reflect on one meaningful quote', min: 'Read one quote' },
  { id: 256, cat: 'mind', emoji: '✨', name: 'Spot 3 moments of beauty', min: 'Notice 1 beautiful thing' },
  { id: 257, cat: 'mind', emoji: '🖐️', name: 'Do 5-4-3-2-1 grounding', min: 'Name 3 things you can see' },
  { id: 258, cat: 'mind', emoji: '✉️', name: 'Check messages at 3 set times', min: 'Skip one inbox check' },
  { id: 259, cat: 'mind', emoji: '🖍️', name: 'Doodle or color 10 minutes', min: 'Doodle for 1 minute' },
  { id: 260, cat: 'mind', emoji: '💗', name: 'Write one self-compassion note', min: 'Write one kind line to yourself' },
  { id: 261, cat: 'mind', emoji: '📆', name: 'Plan something to look forward to', min: 'Name one thing to enjoy' },
  { id: 262, cat: 'mind', emoji: '🎯', name: 'Notice one thing you control', min: 'Name one thing you control' },
  { id: 263, cat: 'mind', emoji: '😂', name: 'Laugh at something funny', min: 'Watch one funny clip' },
  { id: 264, cat: 'mind', emoji: '🌬️', name: 'Take 3 breaths before replying', min: 'One slow breath first' },
  { id: 265, cat: 'mind', emoji: '🪑', name: 'Spend 10 minutes doing nothing', min: 'Do nothing for 1 minute' },
  { id: 266, cat: 'work', emoji: '🐸', name: 'Start with the hardest task', min: 'Open the hardest task' },
  { id: 267, cat: 'work', emoji: '🗓️', name: 'Time-block today\'s schedule', min: 'Block one focus slot' },
  { id: 268, cat: 'work', emoji: '🔕', name: 'Silence notifications for 1 hour', min: 'Mute alerts for 10 minutes' },
  { id: 269, cat: 'work', emoji: '🏆', name: 'Record one work win', min: 'Name one small win' },
  { id: 270, cat: 'work', emoji: '🙏', name: 'Thank one colleague specifically', min: 'Send a one-line thank-you' },
  { id: 271, cat: 'work', emoji: '📰', name: 'Scan industry news 10 min', min: 'Read one industry headline' },
  { id: 272, cat: 'work', emoji: '🏔️', name: 'Review your career goals 5 min', min: 'Reread your top goal' },
  { id: 273, cat: 'work', emoji: '🗂️', name: 'Organize work files 10 min', min: 'File one document' },
  { id: 274, cat: 'work', emoji: '📋', name: 'Write an agenda for one meeting', min: 'Write one agenda bullet' },
  { id: 275, cat: 'work', emoji: '📝', name: 'Send one meeting recap', min: 'Note one action item' },
  { id: 276, cat: 'work', emoji: '📄', name: 'Draft 300 words for work', min: 'Draft 2 sentences' },
  { id: 277, cat: 'work', emoji: '✅', name: 'Update one project tracker', min: 'Update one task status' },
  { id: 278, cat: 'work', emoji: '🎤', name: 'Rehearse a talk for 10 minutes', min: 'Rehearse one opening line' },
  { id: 279, cat: 'work', emoji: '🏢', name: 'Research one target company', min: 'Read one company page' },
  { id: 280, cat: 'work', emoji: '📨', name: 'Tailor one job application', min: 'Tailor one sentence' },
  { id: 281, cat: 'work', emoji: '🤝', name: 'Help one colleague 15 minutes', min: 'Offer help to one person' },
  { id: 282, cat: 'work', emoji: '⏳', name: 'Estimate and time one task', min: 'Estimate one task' },
  { id: 283, cat: 'work', emoji: '🤖', name: 'Automate one repetitive task', min: 'List one task to automate' },
  { id: 284, cat: 'work', emoji: '⚡', name: 'Use one new keyboard shortcut', min: 'Look up one shortcut' },
  { id: 285, cat: 'work', emoji: '📣', name: 'Post one professional insight', min: 'Draft one insight' },
  { id: 286, cat: 'work', emoji: '🧐', name: 'Proofread one key deliverable', min: 'Proofread one paragraph' },
  { id: 287, cat: 'work', emoji: '🪜', name: 'Break one big task into steps', min: 'Write the first step' },
  { id: 288, cat: 'work', emoji: '🗣️', name: 'Speak up once in a meeting', min: 'Prepare one comment' },
  { id: 289, cat: 'work', emoji: '📌', name: 'Follow up on one open loop', min: 'Send one follow-up line' },
  { id: 290, cat: 'work', emoji: '📘', name: 'Document one work process', min: 'Write one process step' },
  { id: 291, cat: 'work', emoji: '📈', name: 'Check one key work metric', min: 'Check one number' },
  { id: 292, cat: 'work', emoji: '💼', name: 'Prepare one interview story', min: 'Note one story idea' },
  { id: 293, cat: 'sleep', emoji: '📖', name: 'Read a paper book in bed', min: 'Read 1 page in bed' },
  { id: 294, cat: 'sleep', emoji: '🚿', name: 'Take a warm shower before bed', min: 'Warm rinse for 2 minutes' },
  { id: 295, cat: 'sleep', emoji: '💡', name: 'Dim lights 1 hour before bed', min: 'Dim one lamp tonight' },
  { id: 296, cat: 'sleep', emoji: '🙆', name: 'Stretch 5 minutes before bed', min: 'Do one bedtime stretch' },
  { id: 297, cat: 'sleep', emoji: '⏰', name: 'Rise at your first alarm', min: 'Sit up at first alarm' },
  { id: 298, cat: 'sleep', emoji: '📓', name: 'Log sleep quality each morning', min: 'Rate last night\'s sleep' },
  { id: 299, cat: 'sleep', emoji: '🍽️', name: 'Finish dinner 2 hours before bed', min: 'Finish dinner 1 hour before bed' },
  { id: 300, cat: 'sleep', emoji: '💤', name: 'Do progressive muscle relaxation', min: 'Relax one muscle group' },
  { id: 301, cat: 'sleep', emoji: '🎧', name: 'Listen to a calm sleep story', min: 'Hear 2 minutes of a story' },
  { id: 302, cat: 'sleep', emoji: '🔕', name: 'Silence notifications at bedtime', min: 'Mute one noisy app' },
  { id: 303, cat: 'sleep', emoji: '🪟', name: 'Air out the bedroom 10 minutes', min: 'Open a window for 2 minutes' },
  { id: 304, cat: 'sleep', emoji: '🦶', name: 'Massage your feet before bed', min: 'Rub your feet for 1 minute' },
  { id: 305, cat: 'sleep', emoji: '📰', name: 'Keep evenings news-free', min: 'Skip one evening headline' },
  { id: 306, cat: 'sleep', emoji: '🦵', name: 'Lie legs-up-the-wall 5 min', min: 'Lie legs-up-the-wall 1 min' },
  { id: 307, cat: 'sleep', emoji: '🛌', name: 'Do a 10-min yoga nidra', min: 'Do 2 minutes of yoga nidra' },
  { id: 308, cat: 'sleep', emoji: '🔀', name: 'Do a cognitive shuffle in bed', min: 'Picture 5 random words' },
  { id: 309, cat: 'sleep', emoji: '🧼', name: 'Wash your face before bed', min: 'Splash water on your face' },
  { id: 310, cat: 'sleep', emoji: '🏝️', name: 'Visualize a calm place in bed', min: 'Imagine a calm place 1 min' },
  { id: 311, cat: 'sleep', emoji: '🔔', name: 'Set a bedtime reminder', min: 'Set a reminder for tonight' },
  { id: 312, cat: 'sleep', emoji: '🔊', name: 'Play white noise at bedtime', min: 'Turn on a fan for sound' },
  { id: 313, cat: 'sleep', emoji: '👕', name: 'Change into sleepwear early', min: 'Lay out your pajamas' },
  { id: 314, cat: 'sleep', emoji: '🧦', name: 'Wear socks to bed', min: 'Put socks by your bed' },
  { id: 315, cat: 'sleep', emoji: '📋', name: 'Write a done list before bed', min: 'Write one thing you finished' },
  { id: 316, cat: 'sleep', emoji: '🕔', name: 'End work at a set time', min: 'Close work apps on time' },
  { id: 317, cat: 'sleep', emoji: '🥪', name: 'Take a full lunch break', min: 'Take 10 minutes away' },
  { id: 318, cat: 'sleep', emoji: '🏝️', name: 'Rest fully for one hour', min: 'Rest for 10 minutes' },
  { id: 319, cat: 'sleep', emoji: '⏰', name: 'Set your alarm across the room', min: 'Move your alarm once' },
  { id: 320, cat: 'create', emoji: '🎨', name: 'Paint for 20 minutes', min: 'Paint for 2 minutes' },
  { id: 321, cat: 'create', emoji: '📜', name: 'Write one short poem', min: 'Write one line of poetry' },
  { id: 322, cat: 'create', emoji: '🎶', name: 'Write song lyrics 10 minutes', min: 'Write one lyric line' },
  { id: 323, cat: 'create', emoji: '🎹', name: 'Compose 8 bars of music', min: 'Hum one new melody' },
  { id: 324, cat: 'create', emoji: '🎤', name: 'Sing for 10 minutes', min: 'Sing one verse' },
  { id: 325, cat: 'create', emoji: '🧶', name: 'Knit or crochet 15 minutes', min: 'Knit or crochet 1 row' },
  { id: 326, cat: 'create', emoji: '🪡', name: 'Sew or embroider 15 minutes', min: 'Sew 5 stitches' },
  { id: 327, cat: 'create', emoji: '🏺', name: 'Shape clay for 15 minutes', min: 'Shape one small form' },
  { id: 328, cat: 'create', emoji: '🪶', name: 'Practice calligraphy 10 minutes', min: 'Letter one word' },
  { id: 329, cat: 'create', emoji: '🖼️', name: 'Edit one photo', min: 'Adjust one photo setting' },
  { id: 330, cat: 'create', emoji: '📹', name: 'Film a 30-second clip', min: 'Film 5 seconds' },
  { id: 331, cat: 'create', emoji: '🎬', name: 'Edit video for 20 minutes', min: 'Trim one clip' },
  { id: 332, cat: 'create', emoji: '🎧', name: 'Record one audio take', min: 'Record 10 seconds of audio' },
  { id: 333, cat: 'create', emoji: '📕', name: 'Write a 100-word micro story', min: 'Write one story sentence' },
  { id: 334, cat: 'create', emoji: '🎭', name: 'Practice acting or improv 10 min', min: 'Act out one line' },
  { id: 335, cat: 'create', emoji: '📣', name: 'Tell a story out loud', min: 'Tell one short anecdote' },
  { id: 336, cat: 'create', emoji: '💻', name: 'Code creatively for 20 minutes', min: 'Change one line of code' },
  { id: 337, cat: 'create', emoji: '🌈', name: 'Explore one new color palette', min: 'Pick 3 colors' },
  { id: 338, cat: 'create', emoji: '📌', name: 'Build a mood board 10 minutes', min: 'Save one inspiring image' },
  { id: 339, cat: 'create', emoji: '📰', name: 'Make one collage page', min: 'Glue one cut-out' },
  { id: 340, cat: 'create', emoji: '🪞', name: 'Recreate a work you admire', min: 'Copy one small detail' },
  { id: 341, cat: 'create', emoji: '🏁', name: 'Finish one small piece', min: 'Add one finishing touch' },
  { id: 342, cat: 'create', emoji: '🧹', name: 'Tidy your creative space', min: 'Put away one tool' },
  { id: 343, cat: 'create', emoji: '🌅', name: 'Create 10 min before screens', min: 'Create 2 min before screens' },
  { id: 344, cat: 'create', emoji: '📋', name: 'Plan tomorrow\'s creative task', min: 'Write one next step' },
  { id: 345, cat: 'create', emoji: '🚶', name: 'Take a 15-minute idea walk', min: 'Walk 5 minutes, mind open' },
  { id: 346, cat: 'create', emoji: '👀', name: 'Describe one scene in words', min: 'Describe one detail' },
  { id: 347, cat: 'connect', emoji: '❓', name: 'Ask someone a deeper question', min: 'Ask one open question' },
  { id: 348, cat: 'connect', emoji: '🔄', name: 'Follow up on someone\'s news', min: 'Ask how one thing went' },
  { id: 349, cat: 'connect', emoji: '💛', name: 'Tell someone why they matter', min: 'Say one thing you value' },
  { id: 350, cat: 'connect', emoji: '🎲', name: 'Play a game together 20 min', min: 'Play one quick round' },
  { id: 351, cat: 'connect', emoji: '🙏', name: 'Thank a worker by name', min: 'Smile and say thanks' },
  { id: 352, cat: 'connect', emoji: '🤝', name: 'Introduce two people who\'d click', min: 'Think of one good match' },
  { id: 353, cat: 'connect', emoji: '🎁', name: 'Plan a surprise for someone', min: 'Jot one surprise idea' },
  { id: 354, cat: 'connect', emoji: '🎧', name: 'Share a song with a friend', min: 'Send one song link' },
  { id: 355, cat: 'connect', emoji: '📸', name: 'Send a friend an old photo', min: 'Pick one old photo' },
  { id: 356, cat: 'connect', emoji: '👟', name: 'Walk with someone 15 minutes', min: 'Walk 5 minutes together' },
  { id: 357, cat: 'connect', emoji: '💬', name: 'Share one honest feeling', min: 'Name one feeling aloud' },
  { id: 358, cat: 'connect', emoji: '📵', name: 'Spend 30 screen-free min together', min: 'Spend 5 screen-free min together' },
  { id: 359, cat: 'connect', emoji: '📖', name: 'Read aloud with someone', min: 'Read one page together' },
  { id: 360, cat: 'connect', emoji: '🍲', name: 'Cook a meal with someone', min: 'Prep one thing together' },
  { id: 361, cat: 'connect', emoji: '📝', name: 'Leave a kind note for someone', min: 'Write a 3-word note' },
  { id: 362, cat: 'connect', emoji: '🎉', name: 'Celebrate someone\'s win', min: 'Send one congrats' },
  { id: 363, cat: 'connect', emoji: '🧭', name: 'Ask a mentor one question', min: 'Draft one question' },
  { id: 364, cat: 'connect', emoji: '🙌', name: 'Volunteer for 30 minutes', min: 'Find one way to help' },
  { id: 365, cat: 'connect', emoji: '🪪', name: 'Remember one new name', min: 'Repeat a name once' },
  { id: 366, cat: 'connect', emoji: '🙋', name: 'Ask for help with one thing', min: 'Ask one small favor' },
  { id: 367, cat: 'connect', emoji: '👵', name: 'Ask an elder about their life', min: 'Ask one story question' },
  { id: 368, cat: 'connect', emoji: '📥', name: 'Reply to one pending message', min: 'Reply with one line' },
  { id: 369, cat: 'connect', emoji: '😊', name: 'Smile at 3 people today', min: 'Smile at one person' },
  { id: 370, cat: 'connect', emoji: '☕', name: 'Take a break with a colleague', min: 'Chat 2 min with a colleague' },
  { id: 371, cat: 'connect', emoji: '📛', name: 'Use someone\'s name warmly', min: 'Learn one new name' },
  { id: 372, cat: 'connect', emoji: '🏠', name: 'Tell someone about your day', min: 'Share one highlight' },
  { id: 373, cat: 'connect', emoji: '🎓', name: 'Teach someone something new', min: 'Share one useful tip' },
  { id: 374, cat: 'home', emoji: '📬', name: 'Open and sort the mail', min: 'Open one piece of mail' },
  { id: 375, cat: 'home', emoji: '🚿', name: 'Quick bathroom wipe-down', min: 'Wipe the bathroom sink' },
  { id: 376, cat: 'home', emoji: '🧹', name: 'Sweep or vacuum one room', min: 'Sweep one corner' },
  { id: 377, cat: 'home', emoji: '🧦', name: 'Put away clean laundry', min: 'Put away 3 items' },
  { id: 378, cat: 'home', emoji: '☎️', name: 'Make one overdue admin call', min: 'Find the number to call' },
  { id: 379, cat: 'home', emoji: '🔑', name: 'Put keys and wallet away', min: 'Hang up your keys' },
  { id: 380, cat: 'home', emoji: '🪟', name: 'Open windows for 10 minutes', min: 'Open one window' },
  { id: 381, cat: 'home', emoji: '🧊', name: 'Clear old food from the fridge', min: 'Check one shelf' },
  { id: 382, cat: 'home', emoji: '👟', name: 'Tidy the entryway', min: 'Line up your shoes' },
  { id: 383, cat: 'home', emoji: '📱', name: 'Tidy your phone home screen', min: 'Delete one unused app' },
  { id: 384, cat: 'home', emoji: '🖼️', name: 'Delete 20 unwanted photos', min: 'Delete 3 photos' },
  { id: 385, cat: 'home', emoji: '💾', name: 'Back up important files', min: 'Back up one file' },
  { id: 386, cat: 'home', emoji: '🔐', name: 'Update one weak password', min: 'Find one weak password' },
  { id: 387, cat: 'home', emoji: '🧻', name: 'List what\'s running low', min: 'Note one item to restock' },
  { id: 388, cat: 'home', emoji: '🪶', name: 'Dust one room', min: 'Dust one shelf' },
  { id: 389, cat: 'home', emoji: '🥘', name: 'Clean as you cook', min: 'Rinse one pan right away' },
  { id: 390, cat: 'home', emoji: '🗄️', name: 'Organize one drawer', min: 'Tidy half a drawer' },
  { id: 391, cat: 'home', emoji: '🪞', name: 'Clean one mirror or window', min: 'Wipe one small spot' },
  { id: 392, cat: 'home', emoji: '📦', name: 'Mail or return one item', min: 'Pack one item to send' },
  { id: 393, cat: 'home', emoji: '👜', name: 'Clear out your bag or car', min: 'Remove one piece of trash' },
  { id: 394, cat: 'home', emoji: '🎒', name: 'Pack your bag the night before', min: 'Put one item in your bag' },
  { id: 395, cat: 'home', emoji: '🔋', name: 'Charge devices in one spot', min: 'Plug in one device there' },
  { id: 396, cat: 'home', emoji: '🔦', name: 'Do a lights-off walkthrough', min: 'Check one door' },
  { id: 397, cat: 'home', emoji: '👐', name: 'Share one chore with someone', min: 'Ask for help with one chore' },
  { id: 398, cat: 'home', emoji: '📋', name: 'Fill out one pending form', min: 'Open the form' },
  { id: 399, cat: 'home', emoji: '🚪', name: 'Wipe door handles and switches', min: 'Wipe one handle' },
  { id: 400, cat: 'home', emoji: '📥', name: 'Clear your downloads folder', min: 'Delete 5 old downloads' },
];

/* Mission archetypes shown in the interview (multi-select, up to 3).
   Each suggests habits from the library and gives the user an identity to grow into. */
const GOAL_TYPES = [
  { id: 'fit',      emoji: '🏆', label: 'Get fit & strong',       identity: 'an athlete',            suggest: [11, 12, 14, 23, 13] },
  { id: 'health',   emoji: '🥗', label: 'Eat & live healthier',   identity: 'someone who respects their body', suggest: [21, 22, 23, 26, 18] },
  { id: 'learn',    emoji: '🧠', label: 'Master a skill',         identity: 'a relentless learner',  suggest: [2, 1, 5, 8, 56] },
  { id: 'lang',     emoji: '🗣️', label: 'Learn a language',       identity: 'a polyglot',            suggest: [3, 5, 7, 10, 1] },
  { id: 'study',    emoji: '🎓', label: 'Pass an exam',           identity: 'a focused scholar',     suggest: [2, 5, 52, 58, 61] },
  { id: 'money',    emoji: '💰', label: 'Save & be frugal',       identity: 'a wealth builder',      suggest: [31, 32, 33, 34, 21] },
  { id: 'career',   emoji: '💼', label: 'Level up my career',     identity: 'a high performer',      suggest: [51, 52, 54, 55, 60] },
  { id: 'business', emoji: '🚀', label: 'Launch a business',      identity: 'a founder',             suggest: [75, 51, 52, 54, 60] },
  { id: 'calm',     emoji: '🧘', label: 'Find calm & focus',      identity: 'a calm mind',           suggest: [41, 42, 43, 45, 46] },
  { id: 'create',   emoji: '🎨', label: 'Create something real',  identity: 'a maker',               suggest: [75, 71, 76, 78, 77] },
  { id: 'read',     emoji: '📖', label: 'Read more books',        identity: 'a reader',              suggest: [1, 46, 64, 7, 80] },
  { id: 'sleep',    emoji: '😴', label: 'Fix my sleep',           identity: 'someone who recovers like a pro', suggest: [61, 62, 63, 64, 67] },
  { id: 'social',   emoji: '❤️', label: 'Stronger relationships', identity: 'a present friend & partner', suggest: [81, 85, 88, 83, 84] },
  { id: 'digital',  emoji: '📵', label: 'Less screen time',       identity: 'someone who owns their attention', suggest: [45, 46, 57, 30, 64] },
  { id: 'organize', emoji: '🏡', label: 'Get organized',          identity: 'someone with their life in order', suggest: [91, 92, 52, 98, 94] },
];

/* ============================================================
   Coach tips — practical behavioral-design library.
   {habit} and {habitLower} are replaced with the user's weakest habit.
   No medical claims, no exaggerated neuroscience.
   ============================================================ */
const COACH_TIPS = [
  { icon: '🧲', title: 'Stack it onto an existing routine',
    body: 'Anchor it to something that already happens daily: “After I pour my morning coffee, I will {habitLower}.” New routines stick fastest when they ride on ones that are already automatic.' },
  { icon: '🤏', title: 'Shrink it to 2 minutes',
    body: 'If “{habit}” keeps losing, make the entry ridiculous: one page, one push-up, one sentence. The goal right now isn’t results — it’s becoming someone who shows up daily.' },
  { icon: '📍', title: 'Name the when & where',
    body: 'Vague plans fail quietly. Decide now: “I will {habitLower} at [time] in [place].” A specific plan removes the decision from the moment — and the moment is where habits die.' },
  { icon: '🪤', title: 'Design the room, not the willpower',
    body: 'Put the cue for “{habit}” where your eyes land — book on the pillow, shoes by the door, app on the first home screen. Make the easy option visible and the distraction invisible.' },
  { icon: '⏱️', title: 'The 20-second rule',
    body: 'Remove 20 seconds of friction from starting “{habitLower}” — and add 20 seconds of friction to whatever usually replaces it. Most habit battles are decided before they begin.' },
  { icon: '🪞', title: 'Act like the person you’re becoming',
    body: 'Stop saying “I’m trying to {habitLower}.” Say “I’m the kind of person who does this.” Each completion is a small vote for that identity — and consistency follows identity.' },
  { icon: '🚫', title: 'Never miss twice',
    body: 'Missing once is an accident. Missing twice is the start of a new pattern. If you skipped “{habitLower}” yesterday, today is non-negotiable — the minimum version counts.' },
  { icon: '🍿', title: 'Pair it with something you enjoy',
    body: 'Only allow a thing you look forward to while doing “{habitLower}” — your favorite playlist, that podcast, the good coffee. The habit borrows the appeal of the treat.' },
  { icon: '🎉', title: 'Mark the win immediately',
    body: 'The instant you finish “{habitLower}”, check it off and take the small moment of credit. An action that visibly counts is an action you’ll repeat.' },
  { icon: '🌅', title: 'Use a fresh start',
    body: 'Mondays, the 1st of the month, the day after a trip — clean-slate moments make restarting easier. If “{habitLower}” has been slipping, relaunch it tomorrow as Day 1, guilt deleted.' },
  { icon: '⛓️', title: 'Don’t break the chain',
    body: 'Your streak on “{habit}” is a chain you can see. The longer it grows, the more you’ll want to protect it — that’s why your Progress grid exists. Keep it visible.' },
  { icon: '🛡️', title: 'Pre-load the obstacle',
    body: 'Decide the rescue plan now: “If [obstacle] happens, then I will {habitLower} at [backup time] instead.” If-then plans move the decision out of the weak moment.' },
  { icon: '🎬', title: 'Rehearse the first 30 seconds',
    body: 'Don’t daydream the result — mentally walk through how “{habitLower}” starts: where you stand, what you grab, the first move. Familiar actions are easier to start.' },
  { icon: '🗣️', title: 'Tell one person',
    body: 'Text someone: “I do {habitLower} daily for 90 days — ask me about it Friday.” A promise made out loud is harder to quietly drop.' },
  { icon: '🔋', title: 'Protect your sleep first',
    body: 'Skipped “{habitLower}” again? Check your sleep before blaming your discipline. A rested mind follows through; a tired one negotiates. One earlier night beats ten motivational videos.' },
  { icon: '📣', title: 'Make the cue specific',
    body: 'Set a named reminder that says the action: not “reminder” but “{habit} — 2-minute version, now.” Specific cues get acted on; vague buzzes get swiped away.' },
  { icon: '🧗', title: 'Park it next to your strongest habit',
    body: 'Look at what you never miss — do “{habitLower}” immediately after it, same order, every time. Strong routines are the best scaffolding for weak ones.' },
  { icon: '💙', title: 'Forgive fast, restart faster',
    body: 'Beating yourself up after missing “{habitLower}” makes quitting more likely. Note it, shrink the habit, take the next rep. The streak that matters most is how fast you get back up.' },
];

/* Coach Q&A — deterministic answers assembled from the user's real stats.
   Placeholders: {weak} {weakPct} {strong} {strongPct} {momentum} {count} {day} {weakMin} */
const COACH_QA = [
  { id: 'behind',   q: 'Why am I falling behind?',
    a: 'Your numbers say it’s not everything — it’s mostly “{weak}” at {weakPct}% this week, while “{strong}” is at {strongPct}%. You don’t have a discipline problem; you have one badly-placed habit. Shrink it to “{weakMin}” for 7 days and attach it to a fixed moment of your day.' },
  { id: 'priority', q: 'Which habit should I prioritize?',
    a: 'Protect “{strong}” — it’s your anchor at {strongPct}%. Then put your energy on “{weak}” ({weakPct}%): do its minimum version, “{weakMin}”, immediately after the anchor. One anchor plus one rescue beats five half-efforts.' },
  { id: 'toomuch',  q: 'Am I trying to do too much?',
    a: 'You’re running {count} habits with a Momentum Score of {momentum}%. The honest read: if momentum sits under 60% for a week, pause everything except your top 3 until they feel automatic — then add back one at a time. Fewer reps, fully kept, builds more than many reps half-kept.' },
  { id: 'easier',   q: 'How do I make it easier to start?',
    a: 'Cut the start cost. Tonight, stage everything “{weak}” needs so tomorrow it takes one move to begin — and commit only to “{weakMin}”. Starting is the whole game; size can come back later.' },
  { id: 'tomorrow', q: 'Give me a realistic plan for tomorrow.',
    a: 'Day {day} plan: ① “{strong}” at its usual time — it’s your sure win. ② “{weak}” immediately after, minimum version only: “{weakMin}”. ③ Everything else stays normal. Two intentional reps and a normal day is a good day.' },
];

/* Daily nudge copy — rotated for reminders & in-app banners. */
const NUDGES = [
  'Day {day} of 90. {left} habit{s} left today — keep going, you’ve got this. ⚡',
  'Small reps, real momentum. {left} to go today. Keep going! 🙌',
  '90-day you is built today. Knock out {left} more — proud of you. 💪',
  'Don’t break the chain — {left} habit{s} between you and a complete day. 🔥',
  'Two minutes counts. Start the smallest one — let’s keep this bread rising. 🍞',
  'Show up sloppy if you must — just show up. {left} left. You’re doing great. ✨',
  'Hey, the arc misses you. {left} habit{s} left — one rep and you’re back. 💛',
];

/* Warm, encouraging one-liners shown after a habit is completed. */
const CHEERS = [
  'Keep going — that’s another vote for who you’re becoming. 🙌',
  'That’s the rep. Momentum loves you right now. ⚡',
  'Let’s keep this bread rising — one more brick in the arc. 🍞',
  'Proud of you. Small reps, real change. 💪',
  'Look at you go — the streak is breathing. 🔥',
  'Done is beautiful. On to the next. ✨',
  'You showed up. That’s the whole game. 💛',
  'Brick by brick, day by day. Nice one. 🧱',
];

/* A fresh insight each day — the variable reward that makes opening Arc90 worth it. */
const DAILY_INSIGHTS = [
  'Identity beats willpower. Every rep is a vote for the person you’re becoming.',
  'Two minutes is the cheat code. Start so small it feels silly — momentum does the rest.',
  'Don’t break the chain. A streak is just a promise you keep to yourself.',
  'Motivation follows action, not the other way around. Move first.',
  'You don’t rise to your goals — you fall to your systems. Trust the arc.',
  'Never miss twice. One slip is an accident; two is the start of a new habit.',
  'Consistency compounds. Boring days are where the real change is built.',
  'The habit you skip today is the one your future self begs you to keep.',
  'Make it obvious, make it easy, make it satisfying. Then just show up.',
  'Discipline is choosing what you want most over what you want now.',
  'Small wins rewire your brain. Celebrate the rep, not just the result.',
  'Show up on the worst days. Those are the ones that define the arc.',
  'Your environment is stronger than your intentions. Set the stage for the win.',
  'Progress, not perfection. A 1% better day, 90 times, changes everything.',
];

/* Short, punchy splash lines — one shows on open, rotating by the day. */
const SPLASH_PHRASES = [
  'Today is a vote for who you’re becoming.',
  'Small reps. Real momentum.',
  'Show up. The rest follows.',
  'Discipline is a gift to your future self.',
  'One day, or day one — go.',
  'Build the arc, brick by brick.',
  'Motivation fades. Systems stay.',
  'Win the morning, win the day.',
  'Don’t break the chain.',
  'Consistency is the cheat code.',
  'Become 1% better today.',
  'The work works. Trust it.',
  'Quiet reps, loud results.',
  'Your streak is watching.',
  'Make it easy. Just begin.',
  'Identity over willpower.',
  'Keep the promise to yourself.',
  'Progress, not perfection.',
  'Earn your evening.',
  '90 days starts now.',
];

/* Quick post-habit check-in: how do you feel after the rep? */
const HABIT_FEELINGS = [
  { id: 'energized', emoji: '⚡', label: 'More energy', energy: 5, mood: 'strong' },
  { id: 'better',    emoji: '🙂', label: 'Better mood', energy: 4, mood: 'steady' },
  { id: 'calm',      emoji: '😌', label: 'Calmer',      energy: 4, mood: 'steady' },
  { id: 'same',      emoji: '😐', label: 'About the same' },
  { id: 'drained',   emoji: '😮‍💨', label: 'Drained',  energy: 2, mood: 'tired' },
];

/* ============================================================
   Protocol Tracker — tracking-only wellness log.
   No recommendations, no dosing, no medical advice.
   ============================================================ */
const PROTOCOL_TYPES = [
  { id: 'vitamin',    label: 'Vitamin',    emoji: '☀️' },
  { id: 'supplement', label: 'Supplement', emoji: '🌿' },
  { id: 'peptide',    label: 'Peptide',    emoji: '🧬' },
  { id: 'medication', label: 'Medication', emoji: '💊' },
  { id: 'nutrition',  label: 'Nutrition',  emoji: '🥗' },
  { id: 'fitness',    label: 'Training',   emoji: '🏋️' },
  { id: 'other',      label: 'Other',      emoji: '📋' },
];

const SYMPTOMS = [
  { id: 'none',      label: 'Feeling fine', flag: false },
  { id: 'nausea',    label: 'Nausea', flag: false },
  { id: 'fatigue',   label: 'Fatigue', flag: false },
  { id: 'headache',  label: 'Headache', flag: false },
  { id: 'dizzy',     label: 'Mild dizziness', flag: false },
  { id: 'appetite',  label: 'Appetite change', flag: false },
  { id: 'sleep',     label: 'Sleep change', flag: false },
  { id: 'mood',      label: 'Mood change', flag: false },
  { id: 'stomach',   label: 'Stomach upset', flag: false },
  { id: 'sev-dizzy', label: 'Severe dizziness', flag: true },
  { id: 'chest',     label: 'Chest pain', flag: true },
  { id: 'breath',    label: 'Trouble breathing', flag: true },
  { id: 'faint',     label: 'Fainting', flag: true },
  { id: 'allergy',   label: 'Allergic reaction', flag: true },
  { id: 'seizure',   label: 'Seizure symptoms', flag: true },
];

const PROTOCOL_DISCLAIMER = 'Track your routine, reminders, symptoms, and notes. Arc90 does not provide medical advice, dosing recommendations, or treatment suggestions. Always follow guidance from a licensed healthcare professional.';

const URGENT_MSG = 'This may need urgent medical attention. Please contact a medical professional or emergency services now.';

const DOSING_BOUNDARY = 'Arc90 can help you track your routine, reminders, symptoms, and notes — but it cannot recommend doses or tell you what to take. For dosing or medical decisions, follow your clinician’s instructions.';

const PROTOCOL_TEMPLATES = [
  { id: 'vit-d3', emoji: '☀️', name: 'Vitamin D3', type: 'vitamin', amount: 'Label or clinician dose', reason: 'vitamin routine', freq: 'Daily', time: '08:00', slot: 'day', notes: 'Take as directed by label or clinician.' },
  { id: 'magnesium', emoji: '🌙', name: 'Magnesium', type: 'supplement', amount: 'Label serving', reason: 'sleep / recovery signal', freq: 'Daily', time: '21:00', slot: 'night', notes: 'Track timing and next-day sleep quality.' },
  { id: 'omega-3', emoji: '🐟', name: 'Omega-3', type: 'supplement', amount: 'Label serving', reason: 'nutrition support', freq: 'Daily', time: '12:00', slot: 'day', notes: 'Track with meals and body signals.' },
  { id: 'creatine', emoji: '⚡', name: 'Creatine', type: 'supplement', amount: 'Label serving', reason: 'training support', freq: 'Daily', time: '10:00', slot: 'day', notes: 'Track consistency and training days.' },
  { id: 'protein', emoji: '🥩', name: 'Protein target', type: 'nutrition', amount: 'Your daily target', reason: 'protein intake', freq: 'Daily', time: '19:00', slot: 'day', notes: 'Log meals or total protein from your own target.' },
  { id: 'water', emoji: '💧', name: 'Water target', type: 'nutrition', amount: 'Your hydration target', reason: 'hydration', freq: 'Daily', time: '14:00', slot: 'day', notes: 'Track cups/ounces privately.' },
  { id: 'electrolytes', emoji: '🧂', name: 'Electrolytes', type: 'supplement', amount: 'Label serving', reason: 'hydration support', freq: 'As needed', time: '12:00', slot: 'flex', notes: 'Track sweat, training, and how you feel.' },
  { id: 'nicotine', emoji: '🚭', name: 'Nicotine use', type: 'other', amount: 'Track use only', reason: 'screen-time / craving awareness', freq: 'As needed', time: '18:00', slot: 'flex', notes: 'Use this as a reduction awareness log, not advice.' },
  { id: 'peptide-plan', emoji: '🧬', name: 'Peptide protocol', type: 'peptide', amount: 'One clinician-directed dose', reason: 'clinician-guided protocol', freq: 'Daily', time: '08:00', slot: 'day', notes: 'Track one daily clinician-guided dose. Do not change dosing without your clinician.' },
  { id: 'training', emoji: '🏋️', name: 'Training session', type: 'fitness', amount: 'Sets, reps, or duration', reason: 'training load', freq: 'Weekly', time: '17:00', slot: 'flex', notes: 'Log workout type, intensity, and recovery.' },
  { id: 'sleep-window', emoji: '🛌', name: 'Sleep window', type: 'other', amount: 'Bedtime / wake target', reason: 'sleep consistency', freq: 'Daily', time: '21:30', slot: 'night', notes: 'Track duration, quality, and next-day energy.' },
  { id: 'caffeine', emoji: '☕', name: 'Caffeine', type: 'nutrition', amount: 'mg from label', reason: 'energy / sleep signal', freq: 'As needed', time: '09:00', slot: 'day', notes: 'Track timing to compare against sleep quality.' },
  { id: 'med-morning', emoji: '💊', name: 'Morning medication', type: 'medication', amount: 'As prescribed', reason: 'prescription adherence', freq: 'Daily', time: '08:00', slot: 'day', notes: 'Track that you took it as prescribed. Arc90 never advises on dosing.' },
  { id: 'med-evening', emoji: '💊', name: 'Evening medication', type: 'medication', amount: 'As prescribed', reason: 'prescription adherence', freq: 'Daily', time: '20:00', slot: 'night', notes: 'Track evening doses as prescribed by your clinician.' },
  { id: 'med-prn', emoji: '💊', name: 'As-needed medication', type: 'medication', amount: 'As prescribed', reason: 'symptom relief tracking', freq: 'As needed', time: '12:00', slot: 'flex', notes: 'Log when you take an as-needed medication. Tracking only, not advice.' },
];

const CHALLENGE_TEMPLATES = [
  { id: 'body-reset', emoji: '🏆', name: 'Body Reset', desc: 'Training, protein, hydration, sleep, and steps.', habits: [11, 12, 21, 23, 61], goal: 'Build a stronger, healthier body in 90 days' },
  { id: 'lean-energy', emoji: '🥗', name: 'Lean Energy', desc: 'Clean meals, vegetables, water, walks, and no late snacking.', habits: [21, 22, 23, 18, 26], goal: 'Feel lighter, cleaner, and more energetic' },
  { id: 'deep-work', emoji: '💼', name: 'Deep Work Sprint', desc: 'Focused work, planning, skill growth, inbox reset, and shipping.', habits: [51, 52, 56, 53, 60], goal: 'Build a focused work system that ships' },
  { id: 'calm-mind', emoji: '🧘', name: 'Calm Mind', desc: 'Meditation, journaling, walks, gratitude, and digital sunset.', habits: [41, 42, 47, 43, 46], goal: 'Become calm, clear, and emotionally steady' },
  { id: 'money-discipline', emoji: '💰', name: 'Money Discipline', desc: 'No-spend days, expense logs, savings, grocery list, and subscription audits.', habits: [31, 32, 34, 37, 36], goal: 'Build financial discipline for the next 90 days' },
  { id: 'iron-discipline', emoji: '⚔️', name: 'Iron Discipline', desc: 'Hard mode: train, early bed, morning light, single-task, no-spend.', habits: [11, 116, 113, 120, 31], goal: 'Forge relentless daily discipline' },
  { id: 'morning-protocol', emoji: '🌅', name: 'Morning Protocol', desc: 'Win the first hour: light, stretch, priority, meditate, make your bed.', habits: [113, 13, 119, 41, 91], goal: 'Own your mornings for 90 days' },
  { id: 'sleep-reset', emoji: '😴', name: 'Sleep Reset', desc: 'Target bedtime, phone out, no late caffeine, digital sunset, evening walk.', habits: [116, 117, 118, 46, 18], goal: 'Fix your sleep and recover deeply' },
  { id: 'creator-streak', emoji: '🎨', name: 'Creator Streak', desc: 'Ship daily: make something, capture ideas, document, deep work, study.', habits: [125, 126, 127, 52, 2], goal: 'Build a daily creative practice' },
  { id: 'connection-90', emoji: '❤️', name: 'Connection 90', desc: 'Invest in people: reach out, call, gratitude, real dinners, compliments.', habits: [122, 123, 43, 88, 124], goal: 'Deepen your relationships over 90 days' },
];
